### ISSUE TITLE
Find the Session-Type declarations

### ISSUE THREAD

**Issue by minolin** [minolin/acplugins#1]
Trying to simplyfiy the session type I wanted to map it to a simple enum, so we can just use SessionTypeEnum.Race or whatvever in code:

{ Practise = 0, Qualifying = 1, Race = 2, Drag = 3, Drift = 4 }

But I don't know the real values, probably they are already used in the server's config.ini

**Comment by ghost** [comment]
cant you grab the trackdata json to gather them?

I have to setup and own local sever this weekend to do some research on the plugin to server capabilities that we currenty have.

**Comment by never-eat-yellow-snow** [comment]
This should be related to this information from the INFO page (<server_ip>:http_port/INFO):

{... "sessiontypes":[2,3] ... }

So I guess 2 means Qualifying and 3 means Race.

**Comment by flitzi** [comment]
```
    /// <summary>
    /// Not sure about Drag and Drift, but those probably don't exist in multiplayer.
    /// </summary>
    public enum SessionTypeEnum : byte { Practice = 1, Qualifying = 2, Race = 3, Drag = 4, Drift = 5 }
```

(Included in pull request)

**Comment by minolin** [comment]
Can copy 2+3, so I'm good with that.
Perfect, thank you.
