### ISSUE TITLE
MinoRatingPlugin: WaitForCleanSessionId()

### ISSUE THREAD

**Issue by flitzi** [minolin/acplugins#11]
Because the messages received from the acServer are now processed in a single thread the WaitForCleanSessionId() should not be needed anymore. In addition if there is an exception with CurrentSessionGuid = LiveDataServer.NewSession(..) the ProcessMessages thread will be stuck in the loop in WaitForCleanSessionId().
So I would suggest removing WaitForCleanSessionId() and _sessionIdPending altogether.

**Comment by minolin** [comment]
True. Good one. 
Thank you
