### ISSUE TITLE
Remove old code (AcServerPluginOld)

### ISSUE THREAD

**Issue by minolin** [minolin/acplugins#14]
Is there a point in not to remove the legacy code for the 1.2.3 compability update?
I didn't maintain the obsolete protocol-dependant code anyways. So using this would be dangerous, I think compile-time errors would be better than runtime ones.

**Comment by flitzi** [comment]
I agree. Better remove AcServerPluginOld.cs and the old AcMessageParser.Activate() method.
I've kept them to make it easier to switch between old and new system. But in the long run any developer should switch to the new PluginManager System anyway.
I've marked some other stuff with [Obsolete]. If you don't need them anymore, feel free to remove them.

**Comment by minolin** [comment]
Should be removed. The harmless obsolete functions are still there.
