### ISSUE TITLE
TODOs after 1.2.3 is released

### ISSUE THREAD

**Issue by minolin** [minolin/acplugins#15]
High priority:
- assign the byte-values to the new ACSP protocols, starting with ACSP_SESSION_INFO
- compare the de/serialization of 
  MsgVersionInfo
  MsgChat
  MsgClientLoaded
  RequestSessionInfo
  MsgError

Low priority:
- implement RequestSetSession
- check for the existance of the ACSP_KICK_USER
- implement PluginManager-methods for the new requests

**Comment by minolin** [comment]
Layer should now at least not fail when working with a 1.2.3 server.

TODOs left:
implement PluginManager-methods for the new requests

**Comment by minolin** [comment]
Left:
- Handle Version + Errors
- The MsgSessionInfo->RequestSetSession is doing strange things with the WaitTime, let's see what the Lord answeres. Currently you should set the WaitTime manually, maybe we just have to convert miliseconds to seconds.

**Comment by never-eat-yellow-snow** [comment]
Just want to let you know: I updated the example code with current examples. I like to see the diffs when a new version arrives.

**Comment by minolin** [comment]
ty neys, forgot about that.
I think we're cool with 1.2.3
