### ISSUE TITLE
Optionally search the server_config.ini without /cfg subdirectory

### ISSUE THREAD

**Issue by minolin** [minolin/acplugins#16]
Marcterv has problems because somehow his setup doesn't use a ac_server_directory/cfg folder.
http://www.assettocorsa.net/forum/index.php?threads/server-plugin-minorating-com-server-admin-thread.25751/#post-520871

Solution 1:
If the file doesn't exist, search again without cfg/

Solution 2:
Force the admins to use ../../cfg as ac_server_directory
Don't like that one

Solution 3:
Introduce a second appSetting "config Folder" with default value "cfg"

Preferences?

**Comment by flitzi** [comment]
Solution 4:
Let the user specify the server_cfg and entry_list as command line arguments (similar to acServer with -c and -e). Has the advantage that the user doesn't need to make several copies of the plugin.exe.

I think 3 or 4 are the way to go, I'm fine with both.

**Comment by flitzi** [comment]
After some thought, scratch Solution 4. Perhaps there are other config settings the admin wants to set differently for each server.

So I would suggest Solution 3, but optionally we could implement command line arguments for the plugin where the admin can specify the app.config to be used, like "plugin.exe Server_01/plugin.exe.config". If not specified the default config next to the plugin.exe is used.

**Comment by minolin** [comment]
I quickhacked #3, but it seems to be broken somehow. We should rewrite that "find the config dir" code, it is a bit messy.

**Comment by minolin** [comment]
I think it's solved for now. Cumbersome to have two directories, but maybe we want to find more than the config one day (think about checksums here).
