### ISSUE TITLE
Disconnect blocks Exception on acsp_version differences

### ISSUE THREAD

**Issue by minolin** [minolin/acplugins#18]
if (this.ProtocolVersion != RequiredProtocolVersion)
                    {
                        this.Disconnect();
                        throw new Exception(string.Format("AcServer protocol version '{0}' is different from the required protocol version '{1}'. Disconnecting...",
                            this.ProtocolVersion, RequiredProtocolVersion));
                    }

Disconnect() won't happen, so no Exception is thrown. Blocking line:

_processMessagesThread.Join(); // make sure thread has terminated

Ideas?

**Comment by flitzi** [comment]
Oops, sorry. I created a deadlock. I will commit a fix shortly.

**Comment by minolin** [comment]
Could be solved by a timeout like 

_processMessagesThread.Join(4000)

Edit: If you have problem finding the root of the problem, is pretty cheap

**Comment by flitzi** [comment]
OK, I've committed a fix, but not yet tested.
If there are still Problems, please reopen issue.
