### ISSUE TITLE
Mother of a bug: Environment.TickCount 

### ISSUE THREAD

**Issue by minolin** [minolin/acplugins#26]
Today I really learnt something. DriverInfo.UpdatePosition() uses

> int currTime lastTime = Environment.TickCount;
> this.lastTime = currTime;

and 

> if (this.lastTime > 0

What I didn't know: TickCount is negative for 25days (in server time). 
https://msdn.microsoft.com/de-de/library/system.environment.tickcount%28v=vs.110%29.aspx

Thomas, you can close this after reading, is already fixed like described in the link. Just wanted to let you know. The resulting bugs could have been very, very difficult to find - had luck and a direct RDP session to the failing server today. Maybe this saves you a lot of time one day :+1:

**Comment by flitzi** [comment]
good find
