### ISSUE TITLE
MsgNewSession TimeOfDay is actually race duration in minutes

### ISSUE THREAD

**Issue by flitzi** [minolin/acplugins#7]
didn't rename because it might cause problems on your end

**Comment by minolin** [comment]
Didn't understand that one, but it's time to throw away the old compability stuff.
You also don't need to do such an effort (although it always makes me smile :+1: )

**Comment by flitzi** [comment]
The property in MsgSessionInfo is called TimeOfDay but this is actually session duration in minutes (qualify, practice), so we should change the name to Duration or something.

**Comment by minolin** [comment]
Ah ty. Yes, makes sense. Renamed to SessionDuration
